with open('ParkSort.csv', encoding="utf-8") as file:
    sortData = file.read()
    sortData = eval(sortData)
    eachsd=[sd for sd in sortData]

    # for esd in eachsd:
    #     for idx in list(esd.keys()):
    #         print(idx, "=", esd.get(idx))
    for esd in eachsd:
        pass
        #sk=list(esd.keys())
        #db=parkInfoDB.objects.create(sk[0]=esd.get(sk[0]),sk[1]=esd.get(sk[1]),sk[2]=esd.get(sk[2]),sk[3]=esd.get(sk[3]),sk[4]=esd.get(sk[4]),sk[5]=esd.get(sk[5]),sk[6]=esd.get(sk[6]),sk[7]=esd.get(sk[7]),sk[8]=esd.get(sk[8]),sk[9]=esd.get(sk[9]),sk[10]=esd.get(sk[10]),sk[11]=esd.get(sk[11]),sk[12]=esd.get(sk[12]),sk[13]=esd.get(sk[13]),sk[14]=esd.get(sk[14]),sk[15]=esd.get(sk[15]),sk[16]=esd.get(sk[16]),sk[17]=esd.get(sk[17]),sk[18]=esd.get(sk[18]),sk[19]=esd.get(sk[19]),sk[20]=esd.get(sk[20]),sk[21]=esd.get(sk[21]),sk[22]=esd.get(sk[22]),sk[23]=esd.get(sk[23]),sk[24]=esd.get(sk[24]),sk[25]=esd.get(sk[25]),sk[26]=esd.get(sk[26]),sk[27]=esd.get(sk[27]),sk[28]=esd.get(sk[28]),sk[29]=esd.get(sk[29]),sk[30]=esd.get(sk[30]),sk[31]=esd.get(sk[31]),sk[32]=esd.get(sk[32]),sk[33]=esd.get(sk[33]),sk[34]=esd.get(sk[34]),sk[35]=esd.get(sk[35]),sk[36]=esd.get(sk[36]),sk[37]=esd.get(sk[37]),sk[38]=esd.get(sk[38]),sk[39]=esd.get(sk[39]),sk[40]=esd.get(sk[40]),sk[41]=esd.get(sk[41]),sk[42]=esd.get(sk[42]),sk[43]=esd.get(sk[43]),sk[44]=esd.get(sk[44]),sk[45]=esd.get(sk[45]))
        #db=parkInfoDB.objects.create(CarParkID=esd.get(sk['CarParkID']),CarParkName=esd.get(sk['CarParkName']),CarParkRegNo=esd.get(sk['CarParkRegNo']),OperatorID=esd.get(sk['OperatorID']),Description=esd.get(sk['Description']),CarParkType=esd.get(sk['CarParkType']),ParkingGuideType=esd.get('ParkingGuideType'),ParkingTypes=esd.get('ParkingTypes'),ParkingSiteTypes=esd.get(sk[8]),ChargeTypes=esd.get(sk[9]),Telephone=esd.get('Telephone'),EmergencyPhone=esd.get('EmergencyPhone'),PositionLat=esd.get('PositionLat'),PositionLon=esd.get('PositionLon'),Email=esd.get('Email']),Address=esd.get('Address'),WebURL=esd.get('WebURL'),FareDescription=esd.get('FareDescription'),SpecialOfferDescription=esd.get('SpecialOfferDescription'),IsFreeParkingOutOfHours=esd.get('IsFreeParkingOutOfHours),VehicleRestriction=esd.get('VehicleRestriction'),IsPublic=esd.get('IsPublic'),OperationType=esd.get('OperationType'),LiveOccuppancyAvailable=esd.get('LiveOccuppancyAvailable'),EVRechargingAvailable=esd.get('EVRechargingAvailable'),MonthlyTicketAvailable=esd.get('MonthlyTicketAvailable'),SeasonTicketAvailable=esd.get('SeasonTicketAvailable'),ReservationAvailable=esd.get('ReservationAvailable'),WheelchairAccessible=esd.get('WheelchairAccessible'),OvernightPermitted=esd.get('OvernightPermitted'),TicketMachine=esd.get('TicketMachine'),Toilet=esd.get(sk[31]),Restaurant=esd.get('Restaurant),GasStation=esd.get('GasStation'),Shop=esd.get('Shop'),Gated=esd.get('Gated'),Lighting=esd.get('Lighting'),SecureParking=esd.get('SecureParking'),TicketOffice=esd.get('TicketOffice'),ProhibitedForAnyHazardousMaterialLoads=esd.get('ProhibitedForAnyHazardousMaterialLoads'),SecurityGuard=esd.get('SecurityGuard'),Supervision=esd.get('Supervision'),LandMark=esd.get('LandMark'),BuildingName=esd.get('BuildingName'),City=esd.get('City'),CityCode=esd.get('CityCode'))

        #print((sk[0],"=",esd.get(sk[0]),sk[1],"=",esd.get(sk[1]),sk[2],"=",esd.get(sk[2]),sk[3],"=",esd.get(sk[3]),sk[4],"=",esd.get(sk[4]),sk[5],"=",esd.get(sk[5]),sk[6],"=",esd.get(sk[6]),sk[7],"=",esd.get(sk[7]),sk[8],"=",esd.get(sk[8]),sk[9],"=",esd.get(sk[9]),sk[10],"=",esd.get(sk[10]),sk[11],"=",esd.get(sk[11]),sk[12],"=",esd.get(sk[12]),sk[13],"=",esd.get(sk[13]),sk[14],"=",esd.get(sk[14]),sk[15],"=",esd.get(sk[15]),sk[16],"=",esd.get(sk[16]),sk[17],"=",esd.get(sk[17]),sk[18],"=",esd.get(sk[18]),sk[19],"=",esd.get(sk[19]),sk[20],"=",esd.get(sk[20]),sk[21],"=",esd.get(sk[21]),sk[22],"=",esd.get(sk[22]),sk[23],"=",esd.get(sk[23]),sk[24],"=",esd.get(sk[24]),sk[25],"=",esd.get(sk[25]),sk[26],"=",esd.get(sk[26]),sk[27],"=",esd.get(sk[27]),sk[28],"=",esd.get(sk[28]),sk[29],"=",esd.get(sk[29]),sk[30],"=",esd.get(sk[30]),sk[31],"=",esd.get(sk[31]),sk[32],"=",esd.get(sk[32]),sk[33],"=",esd.get(sk[33]),sk[34],"=",esd.get(sk[34]),sk[35],"=",esd.get(sk[35]),sk[36],"=",esd.get(sk[36]),sk[37],"=",esd.get(sk[37]),sk[38],"=",esd.get(sk[38]),sk[39],"=",esd.get(sk[39]),sk[40],"=",esd.get(sk[40]),sk[41],"=",esd.get(sk[41]),sk[42],"=",esd.get(sk[42]),sk[43],"=",esd.get(sk[43]),sk[44],"=",esd.get(sk[44]),sk[45],"=",esd.get(sk[45])))

