# Generated by Django 2.2.2 on 2022-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkSpace',
            fields=[
                ('parksid', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
