# Generated by Django 2.2.2 on 2022-03-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdxDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkData',
            fields=[
                ('pid', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('regno', models.CharField(max_length=30)),
                ('operatorID', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('carparktype', models.IntegerField()),
                ('guidetype', models.TextField()),
                ('parkingtype', models.TextField()),
                ('parksitetype', models.TextField()),
                ('chargetype', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
                ('position', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('faredescription', models.TextField()),
                ('isfreeoutofhour', models.IntegerField()),
                ('ispublic', models.IntegerField()),
                ('operationtype', models.IntegerField()),
                ('livespaceavailable', models.IntegerField()),
                ('evrchargeavailable', models.IntegerField()),
                ('monthticketavailable', models.IntegerField()),
                ('seasonticketavailable', models.IntegerField()),
                ('reservationavailable', models.IntegerField()),
                ('wheelchairaccessible', models.IntegerField()),
                ('overnightpermit', models.IntegerField()),
                ('ticketmachine', models.IntegerField()),
                ('toliet', models.IntegerField()),
                ('restaurant', models.IntegerField()),
                ('gasstation', models.IntegerField()),
                ('shop', models.IntegerField()),
                ('gated', models.IntegerField()),
                ('lighting', models.IntegerField()),
                ('secureparking', models.IntegerField()),
                ('ticketoffice', models.IntegerField()),
                ('allowloaddangerobject', models.IntegerField()),
                ('securityguard', models.IntegerField()),
                ('supervision', models.IntegerField()),
                ('city', models.CharField(max_length=13)),
                ('citycode', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='parkSpace',
        ),
    ]
